~ md fixes

diff --git a/bin/pre-commit b/bin/pre-commit
--- a/bin/pre-commit
+++ b/bin/pre-commit
@@ -29,6 +29,13 @@
 		exit 1
 	fi
 
+./vendor/bin/phpmd src text phpmd.xml
+	if [ $? != 0 ]
+	then
+		echo "Fix errors before commit."
+		exit 1
+	fi
+
 ./vendor/bin/phpunit
 	if [ $? != 0 ]
 	then
